name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v1.4.0
      with:
        # Buildx version. Example: v0.3.0
        version: latest
    - name: Run a multi-line script
      run: |
        echo this is echo
        docker buildx ls
