name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v1.4.0
      with:
        # Buildx version. Example: v0.3.0
        version: latest
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
    # ,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6
    - name: For each platform, build
      run: |
        echo this is echo
        ls -la
        docker buildx ls
        docker buildx build --platform linux/amd64,linux/arm64 -t "che-plugin-registry" --file ./build/dockerfiles/Dockerfile --target registry . 
        docker images
        docker inspect "che-plugin-registry:latest"
        
